spring.application.name=cseghrender

<<<<<<< HEAD

=======
>>>>>>> af715b85e042b4042db5c129ca1296ee3b07eb6e
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

<<<<<<< HEAD
server.port=8080
=======
server.port=8080
>>>>>>> af715b85e042b4042db5c129ca1296ee3b07eb6e
